import Navbar from '@/components/shared/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/shared/Footer'
import Banner from '@/components/shared/Banner'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
         <Navbar></Navbar>
         <Banner></Banner>
        { children}
       <Footer></Footer>
        </body>
    </html>
  )
}
