"use client";
import Navbar from '@/components/shared/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/shared/Footer'

import { Provider } from 'react-redux'
import { store } from './Redux/store'

import Banner from '@/components/shared/Banner';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <Provider store={store}>

    <html data-theme="black" lang="en">
      <body >
         <Navbar></Navbar>
         <Banner></Banner>
         { children}
       <Footer></Footer>
        </body>
    </html>
    </Provider>
  )
}
